import sys

from matplotlib import rcParams
from translate import Translator
import matplotlib.pyplot as plt

rcParams.update({
    # Set the plot left margin so that the labels are visible.
    'figure.subplot.left': 0.3,

    # Hide the bottom toolbar.
    'toolbar': 'None'
})


class Plotter(object):
    """An util class to display the classification results."""

    _PAUSE_TIME = 0.05
    """Time for matplotlib to wait for UI event."""

    def __init__(self) -> None:
        fig, self._axes = plt.subplots()
        fig.canvas.manager.set_window_title('Classificação de Audio')

        # Stop the program when the ESC key is pressed.
        def event_callback(event):
            if event.key == 'escape':
                sys.exit(0)

        fig.canvas.mpl_connect('key_press_event', event_callback)

        plt.show(block=False)

    # TODO(khanhlvg): Add type hint for result once ClassificationResult added
    # to tflite_support.task.processor module
    def plot(self, result) -> None:
        def printScore(label_list_array, score_list_array):
            lengthArray = len(label_list_array)
            for i in range(lengthArray):
                print(
                    "A categoria:", label_list_array[i], " Está com Score:", score_list_array[i])

        def translateText(text_label):
            dictionaryClassName = {
                "Speech": "Discurso",
                "Child speech, kid speaking": "Fala de criança, criança falando",
                "Conversation": "Conversação",
                "Narration, monologue": "Narração, monólogo",
                "Babbling": "balbuciando",
                "Speech synthesizer": "Sintetizador de voz",
                "Shout": "Gritar",
                "Bellow": "Abaixo",
                "Whoop": "Grito",
                "Yell": "Gritar",
                "Children shouting": "crianças gritando",
                "Screaming": "gritando",
                "Whispering": "sussurrando",
                "Laughter": "Risada",
                "Baby laughter": "riso de bebê",
                "Giggle": "rir",
                "Snicker": "Snicker",
                "Belly laugh": "gargalhada",
                "Chuckle, chortle": "gargalhada, gargalhada",
                "Crying, sobbing": "Chorando, soluçando",
                "Baby cry, infant cry": "Choro de bebê, choro de bebê",
                "Whimper": "Choramingar",
                "Wail, moan": "Lamentar, gemer",
                "Sigh": "Suspirar",
                "Singing": "Cantoria",
                "Choir": "Coro",
                "Yodeling": "cantando",
                "Chant": "Canto",
                "Mantra": "Mantra",
                "Child singing": "criança cantando",
                "Synthetic singing": "canto sintético",
                "Rapping": "Rap",
                "Humming": "cantarolando",
                "Groan": "Gemido",
                "Grunt": "Grunhido",
                "Whistling": "Assobio",
                "Breathing": "Respirando",
                "Wheeze": "Chiado",
                "Snoring": "Ronco",
                "Gasp": "Suspiro",
                "Pant": "calça",
                "Snort": "bufar",
                "Cough": "Tosse",
                "Throat clearing": "pigarro",
                "Sneeze": "Espirrar",
                "Sniff": "Farejar",
                "Run": "Correr",
                "Shuffle": "Embaralhar",
                "Walk, footsteps": "Caminhar, passos",
                "Chewing, mastication": "Mastigação, mastigação",
                "Biting": "Mordendo",
                "Gargling": "gargarejo",
                "Stomach rumble": "Barulho no estômago",
                "Burping, eructation": "Arrotos, eructação",
                "Hiccup": "Soluço",
                "Fart": "Peidar",
                "Hands": "Mãos",
                "Finger snapping": "estalar de dedos",
                "Clapping": "batendo palmas",
                "Heart sounds, heartbeat": "Sons cardíacos, batimentos cardíacos",
                "Heart murmur": "Sopro cardíaco",
                "Cheering": "Torcendo",
                "Applause": "Aplausos",
                "Chatter": "tagarelar",
                "Crowd": "Multidão",
                "Hubbub, speech noise, speech babble": "Hubbub, ruído de fala, balbucio de fala",
                "Children playing": "Crianças brincando",
                "Animal": "Animal",
                "Domestic animals, pets": "Animais domésticos, animais de estimação",
                "Dog": "Cachorro",
                "Bark": "Latido",
                "Yip": "Yip",
                "Howl": "Uivo",
                "Bow-wow": "uau",
                "Growling": "rosnando",
                "Whimper (dog)": "Chorão (cachorro)",
                "Cat": "Gato",
                "Purr": "Ronronar",
                "Meow": "Miau",
                "Hiss": "Silvo",
                "Caterwaul": "Caterwaul",
                "Livestock, farm animals, working animals": "Gado, animais de fazenda, animais de trabalho",
                "Horse": "Cavalo",
                "Clip-clop": "Clip-clop",
                "Neigh, whinny": "relinchar, relinchar",
                "Cattle, bovinae": "Bovinos, Bovinos",
                "Moo": "moo",
                "Cowbell": "Campainha",
                "Pig": "Porco",
                "Oink": "Oink",
                "Goat": "Cabra",
                "Bleat": "Balir",
                "Sheep": "Ovelha",
                "Fowl": "Galinha",
                "Chicken, rooster": "frango, galo",
                "Cluck": "cacarejar",
                "Crowing, cock-a-doodle-doo": "Cantando, cock-a-doodle-doo",
                "Turkey": "Peru",
                "Gobble": "devorar",
                "Duck": "Pato",
                "Quack": "charlatão",
                "Goose": "Ganso",
                "Honk": "buzina",
                "Wild animals": "Animais selvagens",
                "Roaring cats (lions, tigers)": "Gatos rugindo (leões, tigres)",
                "Roar": "Rugido",
                "Bird": "Pássaro",
                "Bird vocalization, bird call, bird song": "Vocalização de pássaros, canto de pássaros, canto de pássaros",
                "Chirp, tweet": "piar, twittar",
                "Squawk": "Squawk",
                "Pigeon, dove": "pombo, pomba",
                "Coo": "Coo",
                "Crow": "Corvo",
                "Caw": "caw",
                "Owl": "Coruja",
                "Hoot": "vaia",
                "Bird flight, flapping wings": "Vôo de pássaro, batendo asas",
                "Canidae, dogs, wolves": "Canidae, cães, lobos",
                "Rodents, rats, mice": "Roedores, ratos, camundongos",
                "Mouse": "Rato",
                "Patter": "padrão",
                "Insect": "Inseto",
                "Cricket": "Grilo",
                "Mosquito": "Mosquito",
                "Fly, housefly": "Voe, mosca doméstica",
                "Buzz": "Zumbido",
                "Bee, wasp, etc.": "Abelha, vespa, etc.",
                "Frog": "Sapo",
                "Croak": "coaxar",
                "Snake": "Cobra",
                "Rattle": "Chocalho",
                "Whale vocalization": "vocalização de baleia",
                "Music": "Música",
                "Musical instrument": "Instrumento musical",
                "Plucked string instrument": "Instrumento de cordas dedilhadas",
                "Guitar": "Guitarra",
                "Electric guitar": "Guitarra elétrica",
                "Bass guitar": "Baixo",
                "Acoustic guitar": "Violão",
                "Steel guitar, slide guitar": "Guitarra de aço, guitarra slide",
                "Tapping (guitar technique)": "Tapping (técnica de guitarra)",
                "Strum": "Dedilhar",
                "Banjo": "Banjo",
                "Sitar": "cítara",
                "Mandolin": "bandolim",
                "Zither": "Cítara",
                "Ukulele": "cavaquinho",
                "Keyboard (musical)": "Teclado (música)",
                "Piano": "Piano",
                "Electric piano": "Piano elétrico",
                "Organ": "Órgão",
                "Electronic organ": "órgão eletrônico",
                "Hammond organ": "órgão hammond",
                "Synthesizer": "Sintetizador",
                "Sampler": "amostrador",
                "Harpsichord": "Cravo",
                "Percussion": "Percussão",
                "Drum kit": "bateria",
                "Drum machine": "bateria eletrônica",
                "Drum": "Tambor",
                "Snare drum": "caixa",
                "Rimshot": "Rimshot",
                "Drum roll": "Rolo de tambores",
                "Bass drum": "Bumbo",
                "Timpani": "Tímpanos",
                "Tabla": "tabla",
                "Cymbal": "prato",
                "Hi-hat": "Oi chapéu",
                "Wood block": "Bloco de madeira",
                "Tambourine": "Pandeiro",
                "Rattle (instrument)": "Chocalho (instrumento)",
                "Maraca": "Maraca",
                "Gong": "Gongo",
                "Tubular bells": "Sinos tubulares",
                "Mallet percussion": "percussão marreta",
                "Marimba, xylophone": "marimba, xilofone",
                "Glockenspiel": "Glockenspiel",
                "Vibraphone": "Vibrafone",
                "Steelpan": "Panela de aço",
                "Orchestra": "Orquestra",
                "Brass instrument": "instrumento de sopro",
                "French horn": "trompa francesa",
                "Trumpet": "Trompete",
                "Trombone": "Trombone",
                "Bowed string instrument": "Instrumento de corda curvado",
                "String section": "Seção de string",
                "Violin, fiddle": "violino, rabeca",
                "Pizzicato": "pizzicato",
                "Cello": "Violoncelo",
                "Double bass": "Contrabaixo",
                "Wind instrument, woodwind instrument": "Instrumento de sopro, instrumento de sopro",
                "Flute": "Flauta",
                "Saxophone": "Saxofone",
                "Clarinet": "Clarinete",
                "Harp": "Harpa",
                "Bell": "Sino",
                "Church bell": "Sino da igreja",
                "Jingle bell": "Toca o sino",
                "Bicycle bell": "Campainha de bicicleta",
                "Tuning fork": "Diapasão",
                "Chime": "Carrilhão",
                "Wind chime": "carrilhão de vento",
                "Change ringing (campanology)": "Alterar toque (campanologia)",
                "Harmonica": "Harmônica",
                "Accordion": "Acordeão",
                "Bagpipes": "Gaita de fole",
                "Didgeridoo": "Didgeridoo",
                "Shofar": "shofar",
                "Theremin": "Theremin",
                "Singing bowl": "tigela de canto",
                "Scratching (performance technique)": "Coçar (técnica de performance)",
                "Pop music": "Música pop",
                "Hip hop music": "música hip-hop",
                "Beatboxing": "Beatboxing",
                "Rock music": "Musica rock",
                "Heavy metal": "Metal pesado",
                "Punk rock": "punk rock",
                "Grunge": "grunge",
                "Progressive rock": "Rock progressivo",
                "Rock and roll": "Rock and roll",
                "Psychedelic rock": "rock psicodélico",
                "Rhythm and blues": "ritmo e blues",
                "Soul music": "musica soul",
                "Reggae": "reggae",
                "Country": "País",
                "Swing music": "música swing",
                "Bluegrass": "Bluegrass",
                "Funk": "Funk",
                "Folk music": "Música folclórica",
                "Middle Eastern music": "música do oriente médio",
                "Jazz": "Jazz",
                "Disco": "Discoteca",
                "Classical music": "Música clássica",
                "Opera": "Ópera",
                "Electronic music": "Música eletrônica",
                "House music": "musica caseira",
                "Techno": "Techno",
                "Dubstep": "dubstep",
                "Drum and bass": "bateria e baixo",
                "Electronica": "Electronica",
                "Electronic dance music": "música de dança eletrônica",
                "Ambient music": "musica ambiente",
                "Trance music": "Música trance",
                "Music of Latin America": "Música da América Latina",
                "Salsa music": "música salsa",
                "Flamenco": "Flamenco",
                "Blues": "Blues",
                "Music for children": "música para crianças",
                "New-age music": "música da nova era",
                "Vocal music": "Música vocal",
                "A capella": "a capela",
                "Music of Africa": "Música da África",
                "Afrobeat": "afrobeat",
                "Christian music": "música cristã",
                "Gospel music": "Música gospel",
                "Music of Asia": "Música da Ásia",
                "Carnatic music": "musica carnatica",
                "Music of Bollywood": "Música de Bollywood",
                "Ska": "Ska",
                "Traditional music": "Música tradicional",
                "Independent music": "música independente",
                "Song": "Canção",
                "Background music": "Música de fundo",
                "Theme music": "música tema",
                "Jingle (music)": "Jingle (música)",
                "Soundtrack music": "trilha sonora",
                "Lullaby": "Canção de ninar",
                "Video game music": "Música de videogame",
                "Christmas music": "música de Natal",
                "Dance music": "Música de dança",
                "Wedding music": "música de casamento",
                "Happy music": "música feliz",
                "Sad music": "Música triste",
                "Tender music": "Música suave",
                "Exciting music": "Música emocionante",
                "Angry music": "música irada",
                "Scary music": "música assustadora",
                "Wind": "Vento",
                "Rustling leaves": "farfalhar de folhas",
                "Wind noise (microphone)": "Ruído do vento (microfone)",
                "Thunderstorm": "Trovoada",
                "Thunder": "Trovão",
                "Water": "Água",
                "Rain": "Chuva",
                "Raindrop": "pingo de chuva",
                "Rain on surface": "Chuva na superfície",
                "Stream": "Fluxo",
                "Waterfall": "Cachoeira",
                "Ocean": "oceano",
                "Waves, surf": "ondas, surfe",
                "Steam": "Vapor",
                "Gurgling": "borbulhante",
                "Fire": "Fogo",
                "Crackle": "crepitar",
                "Vehicle": "Veículo",
                "Boat, Water vehicle": "Barco, Veículo aquático",
                "Sailboat, sailing ship": "Veleiro, veleiro",
                "Rowboat, canoe, kayak": "Barco a remo, canoa, caiaque",
                "Motorboat, speedboat": "lancha, lancha",
                "Ship": "Enviar",
                "Motor vehicle (road)": "Veículo motorizado (estrada)",
                "Car": "Carro",
                "Vehicle horn, car horn, honking": "Buzina de veículo, buzina de carro, buzina",
                "Toot": "Toot",
                "Car alarm": "Alarme de carro",
                "Power windows, electric windows": "Vidros elétricos, vidros elétricos",
                "Skidding": "derrapagem",
                "Tire squeal": "guincho de pneu",
                "Car passing by": "carro passando",
                "Race car, auto racing": "Carro de corrida, automobilismo",
                "Truck": "Caminhão",
                "Air brake": "Freio a ar",
                "Air horn, truck horn": "Buzina a ar, buzina de caminhão",
                "Reversing beeps": "Bipes reversos",
                "Ice cream truck, ice cream van": "Caminhão de sorvete, van de sorvete",
                "Bus": "Ônibus",
                "Emergency vehicle": "veículo de emergência",
                "Police car (siren)": "Carro de polícia (sirene)",
                "Ambulance (siren)": "Ambulância (sirene)",
                "Fire engine, fire truck (siren)": "Carro de bombeiros, caminhão de bombeiros (sirene)",
                "Motorcycle": "Motocicleta",
                "Traffic noise, roadway noise": "Ruído do tráfego, ruído da estrada",
                "Rail transport": "Transporte ferroviário",
                "Train": "Trem",
                "Train whistle": "apito do trem",
                "Train horn": "buzina de trem",
                "Railroad car, train wagon": "Vagão de trem, vagão de trem",
                "Train wheels squealing": "Rodas de trem rangendo",
                "Subway, metro, underground": "Metrô, metrô, subterrâneo",
                "Aircraft": "Aeronave",
                "Aircraft engine": "Motor de aeronave",
                "Jet engine": "motor a jato",
                "Propeller, airscrew": "Hélice, hélice",
                "Helicopter": "Helicóptero",
                "Fixed-wing aircraft, airplane": "Aeronave de asa fixa, avião",
                "Bicycle": "Bicicleta",
                "Skateboard": "Skate",
                "Engine": "Motor",
                "Light engine (high frequency)": "Motor leve (alta frequência)",
                "Dental drill, dentist's drill": "Broca de dentista, broca de dentista",
                "Lawn mower": "cortador de grama",
                "Chainsaw": "Motosserra",
                "Medium engine (mid frequency)": "Motor médio (frequência média)",
                "Heavy engine (low frequency)": "Motor pesado (baixa frequência)",
                "Engine knocking": "Motor batendo",
                "Engine starting": "Partida do motor",
                "Idling": "marcha lenta",
                "Accelerating, revving, vroom": "Acelerando, acelerando, vroom",
                "Door": "Porta",
                "Doorbell": "campainha",
                "Ding-dong": "Ding-dong",
                "Sliding door": "Porta deslizante",
                "Slam": "bater",
                "Knock": "Bater",
                "Tap": "Tocar",
                "Squeak": "Rangido",
                "Cupboard open or close": "Armário aberto ou fechado",
                "Drawer open or close": "Gaveta aberta ou fechada",
                "Dishes, pots, and pans": "Pratos, panelas e frigideiras",
                "Cutlery, silverware": "Talheres, talheres",
                "Chopping (food)": "Cortar (comida)",
                "Frying (food)": "Fritura (comida)",
                "Microwave oven": "Forno de micro-ondas",
                "Blender": "Liquidificador",
                "Water tap, faucet": "Torneira de água, torneira",
                "Sink (filling or washing)": "Pia (encher ou lavar)",
                "Bathtub (filling or washing)": "Banheira (encher ou lavar)",
                "Hair dryer": "Secador de cabelo",
                "Toilet flush": "Descarga",
                "Toothbrush": "Escova de dente",
                "Electric toothbrush": "Escova de dentes elétrica",
                "Vacuum cleaner": "Aspirador de pó",
                "Zipper (clothing)": "Zíper (roupas)",
                "Keys jangling": "Chaves tilintantes",
                "Coin (dropping)": "Moeda (caindo)",
                "Scissors": "Tesoura",
                "Electric shaver, electric razor": "Barbeador elétrico, barbeador elétrico",
                "Shuffling cards": "Embaralhar cartas",
                "Typing": "Digitando",
                "Typewriter": "Máquina de escrever",
                "Computer keyboard": "teclado de computador",
                "Writing": "Escrita",
                "Alarm": "Alarme",
                "Telephone": "Telefone",
                "Telephone bell ringing": "Toque de campainha de telefone",
                "Ringtone": "toque",
                "Telephone dialing, DTMF": "Marcação telefónica, DTMF",
                "Dial tone": "tom de discagem",
                "Busy signal": "Sinal ocupado",
                "Alarm clock": "Despertador",
                "Siren": "sirene",
                "Civil defense siren": "sirene da defesa civil",
                "Buzzer": "campainha",
                "Smoke detector, smoke alarm": "Detector de fumaça, alarme de fumaça",
                "Fire alarm": "Alarme de incêndio",
                "Foghorn": "Foghorn",
                "Whistle": "Assobiar",
                "Steam whistle": "apito a vapor",
                "Mechanisms": "Mecanismos",
                "Ratchet, pawl": "catraca, lingueta",
                "Clock": "Relogio",
                "Tick": "Marcação",
                "Tick-tock": "Tic-tac",
                "Gears": "Engrenagens",
                "Pulleys": "Polias",
                "Sewing machine": "Máquina de costura",
                "Mechanical fan": "ventilador mecanico",
                "Air conditioning": "Ar condicionado",
                "Cash register": "Caixa registradora",
                "Printer": "Impressora",
                "Camera": "Câmera",
                "Single-lens reflex camera": "Câmera reflex de lente única",
                "Tools": "Ferramentas",
                "Hammer": "Martelo",
                "Jackhammer": "britadeira",
                "Sawing": "Serrar",
                "Filing (rasp)": "Arquivamento (raspa)",
                "Sanding": "Lixar",
                "Power tool": "Ferramenta de poder",
                "Drill": "Furar",
                "Explosion": "Explosão",
                "Gunshot, gunfire": "Tiro, tiroteio",
                "Machine gun": "Metralhadora",
                "Fusillade": "Fuzilaria",
                "Artillery fire": "fogo de artilharia",
                "Cap gun": "Cap arma",
                "Fireworks": "Fogos de artifício",
                "Firecracker": "bombinha",
                "Burst, pop": "Estourar, estourar",
                "Eruption": "Erupção",
                "Boom": "estrondo",
                "Wood": "Madeira",
                "Chop": "Cortar",
                "Splinter": "Lasca",
                "Crack": "Rachadura",
                "Glass": "Vidro",
                "Chink, clink": "Chinch, tilintar",
                "Shatter": "quebrar",
                "Liquid": "Líquido",
                "Splash, splatter": "Respingo, respingo",
                "Slosh": "Slosh",
                "Squish": "Squish",
                "Drip": "Pingar",
                "Pour": "Derramar",
                "Trickle, dribble": "Gotejamento, drible",
                "Gush": "Gush",
                "Fill (with liquid)": "Encha (com líquido)",
                "Spray": "spray",
                "Pump (liquid)": "Bomba (líquido)",
                "Stir": "Mexer",
                "Boiling": "Ebulição",
                "Sonar": "Sonar",
                "Arrow": "Seta",
                "Whoosh, swoosh, swish": "Whoosh, swoosh, swish",
                "Thump, thud": "Baque, baque",
                "Thunk": "Tunk",
                "Electronic tuner": "afinador eletrônico",
                "Effects unit": "unidade de efeitos",
                "Chorus effect": "efeito de refrão",
                "Basketball bounce": "salto de basquete",
                "Bang": "estrondo",
                "Slap, smack": "Tapa, tapa",
                "Whack, thwack": "Baque, baque",
                "Smash, crash": "Esmagar, bater",
                "Breaking": "Quebra",
                "Bouncing": "quicando",
                "Whip": "Chicote",
                "Flap": "Aba",
                "Scratch": "Arranhar",
                "Scrape": "Raspar",
                "Rub": "Esfregar",
                "Roll": "Rolar",
                "Crushing": "Esmagamento",
                "Crumpling, crinkling": "Amassar, enrugar",
                "Tearing": "Rasgando",
                "Beep, bleep": "Bipe, bipe",
                "Ping": "Ping",
                "Ding": "Ding",
                "Clang": "Clang",
                "Squeal": "Guincho",
                "Creak": "Ranger",
                "Rustle": "farfalhar",
                "Whir": "zumbido",
                "Clatter": "Barulho",
                "Sizzle": "Chiar",
                "Clicking": "clicando",
                "Clickety-clack": "Clicke-clack",
                "Rumble": "Estrondo",
                "Plop": "plop",
                "Jingle, tinkle": "Tinir, tinir",
                "Hum": "Zumbir",
                "Zing": "Zing",
                "Boing": "Boing",
                "Crunch": "Crunch",
                "Silence": "Silêncio",
                "Sine wave": "onda senoidal",
                "Harmonic": "harmônico",
                "Chirp tone": "tom chilrear",
                "Sound effect": "Efeito sonoro",
                "Pulse": "Pulso",
                "Inside, small room": "No interior, pequena sala",
                "Inside, large room or hall": "No interior, grande sala ou hall",
                "Inside, public space": "No interior, espaço público",
                "Outside, urban or manmade": "Exterior, urbano ou artificial",
                "Outside, rural or natural": "Fora, rural ou natural",
                "Reverberation": "Reverberação",
                "Echo": "Eco",
                "Noise": "Barulho",
                "Environmental noise": "ruído ambiental",
                "Static": "Estático",
                "Mains hum": "Zumbido da rede",
                "Distortion": "Distorção",
                "Sidetone": "Sidetone",
                "Cacophony": "Cacofonia",
                "White noise": "ruído branco",
                "Pink noise": "ruído rosa",
                "Throbbing": "latejante",
                "Vibration": "Vibração",
                "Television": "Televisão",
                "Radio": "Rádio",
                "Field recording": "Gravação de campo",
            }
            if(dictionaryClassName[text_label] == ""):
                return "Não identificado"
            else:
                return dictionaryClassName[text_label]
        """Plot the audio classification result.

        Args:
            result: Classification results returned by an audio classification
            model.
        """
        # Clear the axes
        self._axes.cla()
        self._axes.set_title('O Audio é:')
        self._axes.set_xlim((0, 1))

        # Plot the results so that the most probable category comes at the top.
        classification = result.classifications[0]
        label_list = [translateText(category.category_name)
                      for category in classification.categories]
        score_list = [category.score for category in classification.categories]
        printScore(label_list[::-1], score_list[::-1])
        self._axes.barh(label_list[::-1], score_list[::-1])

        # Wait for the UI event.
        plt.pause(self._PAUSE_TIME)
